version: "2"

services:
    docs:
        build:
            target: base
            context: .
            dockerfile: Dockerfile
        env_file: .env
        command: docker:start
        tty: true
        volumes:
            - ./:/opt/app
        ports:
            - "$EXPOSED_DOCUSAURUS_PORT:3000"
